import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import { ThemeProvider } from "next-themes";

const poppins = Poppins({
  weight: ["400", "600", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Konnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={
        cn(
          "",
          poppins.className
        )}>
          {children}
      </body>
    </html>
  );
}
